ARDUINO_DIR = /opt/arduino-1.8.12
BOARD_TAG = nano
MCU = atmega328p
AVRDUDE_ARD_BAUDRATE = 57600
AVRDUDE_ARD_PROGRAMMER = arduino
ARDUINO_LIBS = 
MONITOR_PORT = /dev/ttyUSB0
OPTIMIZATION_LEVEL = s
include /usr/share/arduino/Arduino.mk
