ARDUINO_DIR = /opt/arduino-1.8.5
BOARD_TAG = mega
MCU = atmega2560
AVRDUDE_ARD_BAUDRATE = 115200
AVRDUDE_ARD_PROGRAMMER = wiring
ARDUINO_LIBS = 
MONITOR_PORT = /dev/ttyUSB0
# OPTIMIZATION_LEVEL = s
include /usr/share/arduino/Arduino.mk
